config/routes.rb
Tagger::Application.routes.draw do
 
  devise_for :patrons, :controllers => { :omniauth_callbacks => "patrons/omniauth_callbacks" }

  match 't', :to => 'tag#new'
  match '/', :to => 'tag#help'
  
  resources :patrons

  resources :bookmarks

  root :to => 'patrons#index'

  match 'remote/:action', :controller => 'remote'

  match 'save', :to => 'bookmarks#new'
  
  match 's/:s', :to => 'remote#service'
  match 's', :to => 'remote#service'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  
  acts_as_taggable
  has_and_belongs_to_many :patrons, :uniq => true
  
  before_save :parse_original_url
  
  def link
    self.original_url
  end
  
  def display_link
    self.original_url.gsub(/^http:\/\/([^\/]*).*$/, '\1')
  end
  
private 

  # Takes a URL and decides which type of bookmark it is
  def parse_original_url
    self.title ||= self.original_url
    case self.original_url
    when /digitalgallery\.nypl\.org/ && /imageID/
      self.type = "DgImage"
      self.remote_ref = self.original_url.gsub(/^.*imageID=([^&]+).*$/, '\1')
      self.title.gsub!("NYPL Digital Gallery | ", "")
    when /ebooks\.nypl\.org/ && /ContentDetails/
      self.type = "Ebook"
      self.remote_ref = self.original_url.gsub(/^.*ContentDetails.htm?id=([^&]+).*$/, '\1')
      self.title.gsub!("The New York Public Library, eNYPL - ", "")
    when /catalog\.nypl\.org/
      self.type = "BibRecord"
    when /nypl\.org\/locations/
      self.type = "LibLocation"
      self.title.gsub!(" | The New York Public Library", "")
    when /nypl\.org\/events\/.*\/\d\d\d\d\/\d\d\/\d\d/
      self.type = "Event"
      date = url.gsub(/^.*nypl\.org\/events\/.*\/(\d\d\d\d)\/(\d\d)\/(\d\d).*/, '\2-\3-\1')
      self.title.gsub!(" | The New York Public Library", "")
      self.title = "#{date}: #{self.title}"
    else
      self.type = "Bookmark"
      self.title.gsub!(" | The New York Public Library", "")
    end
  end
  
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = Bookmark.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookmarks }
    end
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/new
  # GET /bookmarks/new.json
  def new
    @bookmark = Bookmark.new
    @bookmark.original_url = params[:url]
    respond_to do |format|
      format.html { render :layout => "mini" }
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/1/edit
  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(params[:bookmark])
    @bookmark.tag_list = params[:tags]

    if @bookmark.save
      flash[:notice] =  'Bookmark was successfully created.'
    end
  end

  # PUT /bookmarks/1
  # PUT /bookmarks/1.json
  def update
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      if @bookmark.update_attributes(params[:bookmark])
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to bookmarks_url }
      format.json { head :ok }
    end
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for(@bookmark, :remote => true) do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
   URL:  <span id="bookmark_link"><%= @bookmark[:original_url] %></span>
    <%= f.hidden_field :original_url %>
  </div>
  <div class="field">
	<%= text_field_tag "tags", "", {:placeholder=>"Type a tag"} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookmarks/create.js.erb
self.close();

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<h1>Listing bookmarks</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Uuid</th>
    <th>Remote ref</th>
  </tr>

<% for bookmark in @bookmarks %>
  <tr>
    <td><%=h bookmark.type %></td>
    <td><%=h bookmark.uuid %></td>
    <td><%=h bookmark.remote_ref %></td>
    <td><%= link_to 'Show', bookmark %></td>
    <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
    <td><%= link_to 'Destroy', bookmark, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render 'form' %>

app/views/bookmarks/show.html.erb
<p>
  <b>Type:</b>
  <%=h @bookmark.type %>
</p>

<p>
  <b>Uuid:</b>
  <%=h @bookmark.uuid %>
</p>

<p>
  <b>Remote ref:</b>
  <%=h @bookmark.remote_ref %>
</p>


<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>