config/routes.rb
Tagger::Application.routes.draw do
 
  devise_for :patrons, :controllers => { :omniauth_callbacks => "patrons/omniauth_callbacks" }

  match 't', :to => 'tag#new'
  match '/', :to => 'tag#help'
  
  resources :patrons

  resources :bookmarks

  root :to => 'patrons#index'

  match 'remote/:action', :controller => 'remote'

  match 'save', :to => 'bookmarks#new'
  
  match 's/:s', :to => 'remote#service'
  match 's', :to => 'remote#service'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tagger</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
	<% end %>
	<% if flash[:alert] %>
	<div class="alert"><%= flash[:alert] %></div>
	<% end %>

	<div id="main">
		<div id="toolbar">

			<%= link_to_unless_current "Your Favorites", current_patron %> •
			<%= link_to_unless_current "Latest activity", patrons_path %> •

			<div class="left_stuff">
				<% if patron_signed_in? %>
				<%= link_to_unless_current "My Account", edit_patron_path(current_patron), :target => "_top" %> •
				<%= link_to('Logout', destroy_patron_session_path, :method => :delete) %> 
				<% else %>
				<%= link_to "Sign in with Google", patron_omniauth_authorize_path(:google) %>
				<% end %>
			</div>
		</div>
		<%= yield  %>
	</div>
	<%= debug current_patron.inspect %>

</body>
</html>

app/views/layouts/mini.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tagger</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
	<% end %>

	<div id="main">
		<%= yield  %>
	</div>

</body>
</html>